/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodigoShopifyRouteImport } from './routes/codigo-shopify'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as ProductsHandleRouteImport } from './routes/products.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodigoShopifyRoute = CodigoShopifyRouteImport.update({
  id: '/codigo-shopify',
  path: '/codigo-shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codigo-shopify': typeof CodigoShopifyRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codigo-shopify': typeof CodigoShopifyRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codigo-shopify': typeof CodigoShopifyRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codigo-shopify'
    | '/collections/$slug'
    | '/pages/$slug'
    | '/products/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/codigo-shopify'
    | '/collections/$slug'
    | '/pages/$slug'
    | '/products/$handle'
  id:
    | '__root__'
    | '/'
    | '/codigo-shopify'
    | '/collections/$slug'
    | '/pages/$slug'
    | '/products/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodigoShopifyRoute: typeof CodigoShopifyRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  PagesSlugRoute: typeof PagesSlugRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigo-shopify': {
      id: '/codigo-shopify'
      path: '/codigo-shopify'
      fullPath: '/codigo-shopify'
      preLoaderRoute: typeof CodigoShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodigoShopifyRoute: CodigoShopifyRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  PagesSlugRoute: PagesSlugRoute,
  ProductsHandleRoute: ProductsHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
